export const SET_AUTHENTICATE = "SET_AUTHENTICATE";
export const SET_CURRENT_USER_ON_SITE_RELOAD =
  "SET_CURRENT_USER_ON_SITE_RELOAD";

// export const SET_AUTHENTICATE_MANUALLY = "SET_AUTHENTICATE_MANUALLY";

// export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const LOAD_PRODUCTS_LIST = "LOAD_PRODUCTS_LIST";
export const LOAD_PRODUCTS_LIST_FETCH_ERROR = "LOAD_PRODUCTS_LIST_FETCH_ERROR";
export const ADD_TO_PRODUCT_LIST = "ADD_TO_PRODUCT_LIST";
export const ADD_TO_PRODUCT_LIST_FETCH_ERROR =
  "ADD_TO_PRODUCT_LIST_FETCH_ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_FETCH_ERROR = "DELETE_PRODUCT_FETCH_ERROR";

export const REGISTER = "REGISTER";

export const LOAD_CART_ITEMS = "LOAD_CART_ITEMS";
export const LOAD_CART_ITEMS_FETCH_ERROR = "LOAD_CART_ITEMS_FETCH_ERROR";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_ITEM_TO_CART_FETCH_ERROR = "ADD_ITEM_TO_CART_FETCH_ERROR";

export const INCREMENT_CART_ITEM_QTY = "INCREMENT_CART_ITEM_QTY";
