export const SET_AUTHENTICATE = "SET_AUTHENTICATE";
export const SET_CURRENT_USER_ON_SITE_RELOAD =
  "SET_CURRENT_USER_ON_SITE_RELOAD";

// export const SET_AUTHENTICATE_MANUALLY = "SET_AUTHENTICATE_MANUALLY";

// export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const LOAD_PRODUCTS_LIST = "LOAD_PRODUCTS_LIST";
export const LOAD_PRODUCTS_LIST_FETCH_ERROR = "LOAD_PRODUCTS_LIST_FETCH_ERROR";
export const ADD_TO_PRODUCT_LIST = "ADD_TO_PRODUCT_LIST";
export const ADD_TO_PRODUCT_LIST_FETCH_ERROR =
  "ADD_TO_PRODUCT_LIST_FETCH_ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_FETCH_ERROR = "DELETE_PRODUCT_FETCH_ERROR";

export const REGISTER = "REGISTER";

export const LOAD_CART_ITEMS = "LOAD_CART_ITEMS";
export const LOAD_CART_ITEMS_FETCH_ERROR = "LOAD_CART_ITEMS_FETCH_ERROR";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_ITEM_TO_CART_FETCH_ERROR = "ADD_ITEM_TO_CART_FETCH_ERROR";

export const INCREMENT_CART_ITEM_QTY = "INCREMENT_CART_ITEM_QTY";
export const DECREMENT_CART_ITEM_QTY = "DECREMENT_CART_ITEM_QTY";

export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const UPDATE_CART_ITEM_FETCH_ERROR = "UPDATE_CART_ITEM_FETCH_ERROR";

export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_CART_ITEM_FETCH_ERROR = "DELETE_CART_ITEM_FETCH_ERROR";

export const CHECKOUT_CART = "CHECKOUT_CART";
export const CHECKOUT_CART_FETCH_ERROR = "CHECKOUT_CART_FETCH_ERROR";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SET_USER_CART_ID = "SET_USER_CART_ID";
export const SET_USER_CART_ID_FETCH_ERROR = "SET_USER_CART_ID_FETCH_ERROR";
