export const SET_AUTHENTICATE = "SET_AUTHENTICATE";
export const SET_AUTHENTICATE_MANUALLY = "SET_AUTHENTICATE_MANUALLY";

export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";
export const ADD_TO_PRODUCT_LIST = "ADD_TO_PRODUCT_LIST";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const REGISTER = "REGISTER";
